SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

-- 이름과 급여정보를 조회
SELECT FIRST_NAME, SALARY FROM EMPLOYEES;


SELECT DISTINCT DEPARTMENT_ID 
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC;

-- 이름, 급여, 부서번호를 이름순으로 오름차순해서 조회
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY FIRST_NAME;  
  
-- 별칭 사용
SELECT FIRST_NAME AS 이름, SALARY AS 급여, DEPARTMENT_ID 부서번호
FROM EMPLOYEES
ORDER BY FIRST_NAME;

-- 별칭에 큰따옴표를 써야하는 경우 : 특수문자, 띄어쓰기 등이 포함될 경우 
SELECT FIRST_NAME AS "이름 ♥", SALARY AS "급 여", DEPARTMENT_ID 부서번호
FROM EMPLOYEES
ORDER BY FIRST_NAME; 

-- [문제] 직원의 급여의 5%를 보너스로 지급하려고 한다.
-- 직원의 사원번호, 이름, 급여, 보너스, 합계
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, SALARY*0.05 AS BONUS, SALARY + SALARY*0.05 AS TOTAL
FROM EMPLOYEES;

-- 직원명 뒤에 '님'을 붙여 조회하시오
SELECT FIRST_NAME || '님' AS "이름"
FROM EMPLOYEES;

-- '이름 성'을 붙여서 조회하시오
SELECT FIRST_NAME || ' ' || LAST_NAME
  FROM EMPLOYEES;

-- 급여가 10000 이상인 사람들의 사원번호, 이름, 급여, 직급을 조회하시오
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY >= 10000;

-- 급여가 10000 이상인 사람들의 사원번호, 이름, 급여, 직급을  급여가 많은 순으로 조회하시오
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY >= 10000
ORDER BY SALARY DESC;

-- 사원번호, 이름, 급여, 부서번호를 조회. 부서번호가 80번인 데이터를 조회
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;


-- 급여가 5000~10000 이상인 사람들의 사원번호, 이름, 급여, 직급을 조회하시오
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY >= 5000 AND SALARY <= 10000;

-- 부서번호가 10이거나 50인 부서에 속한 직원들의 이름, 부서번호를 조회하시오.
SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 50;


-- 부서번호가 10이나 50이 아닌 부서에 속한 직원들의 이름, 부서번호를 조회하시오.
SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE NOT(DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 50);

-- 위의 코드를 부서별로 오름차순 정렬
SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE NOT(DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 50)
ORDER BY 0;
  
-- 이름, 급여, 커미션을 조회하시오
SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES;
  
-- 이름, 급여, 커미션을 조회하시오 (커미션을 받는 사람)
SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT != NULL;  

SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;  
  
SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;  

-- 매니저가 없는 직원의 이름, 직급을 조회하시오.
SELECT FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_iD IS NULL;

-- 이름, 급여, 커미션금액, 총수령액을 조회 (단, 커미션이 있는 사람)
SELECT FIRST_NAME, SALARY, COMMISSION_PCT*SALARY AS "커미션 금액", 
			 SALARY + COMMISSION_PCT*SALARY AS "총수령액"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

-- 급여가 10000~15000 사이인 직원의 이름, 급여를 조회
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 15000;

-- 부서번호가 10이거나 50인 부서에 속한 직원들의 이름, 부서번호를 조회하시오.
SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 50);

-- 급여가 7000을 초과하고 이메일이 'SKING' 인 직원의 이름, 전화번호, 이메일 조회
SELECT FIRST_NAME, PHONE_NUMBER, EMAIL
FROM EMPLOYEES
WHERE SALARY > 7000 AND EMAIL = 'SKING';

-- 직원의 이름과 입사일을 조회하시오. (입사일 순)
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE;


-- 직원의 이름과 입사일을 조회하시오
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES;

-- 직원의 이름과 입사일 07년도에 입사한 사람만 조회 '07/01/01'~'07/12/31'
--   (입사일 순)
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '07/01/01' AND '07/12/31'
ORDER BY HIRE_DATE;

-- 직원의 이름과 입사일 07년도에 이전에 입사한 사람만 조회  (입사일 순)
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE < '07/01/01' 
ORDER BY HIRE_DATE;

-- 날짜 데이터를 산술연산?
SELECT FIRST_NAME, HIRE_DATE, HIRE_DATE+1
FROM EMPLOYEES;

-- 직원의 이름이 'J'로 시작하는 직원을 조회 (직원명)
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'J%';
  
-- 직원의 이름이 'n'로 끝나는 직원을 조회 (직원명)
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n';

-- 직원의 이름이 'n'로 끝나면서 이름의 길이가 5인 직원을 조회 (직원명)
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '____n';

-- 직원의 이름과 입사일 07년도에 입사한 사람만 조회 LIKE 이용   (입사일 순)
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '07%'
ORDER BY HIRE_DATE;

-- 직원의 이름과 입사일 1월에 입사한 사람만 조회 LIKE 이용 (입사일 순)
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%/01/%'
ORDER BY HIRE_DATE;

-- [연습]
-- 1) 매니저가 103인 직원의 정보(아이디, 이름, 부서, 매니저번호)를 조회하시오.
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID = 103;

-- 2) 어느 부서에도 속하지 않은 직원의 정보 (이름, 전화번호, 부서)를 조회하시오
SELECT FIRST_NAME, PHONE_NUMBER, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

-- 3) 급여가 10000을 초과하면서 JOB_ID가 'SA_REP'인 사람의 이메일, 이름, 전화번호, JOB_ID 정보를 조회하시오
SELECT EMAIL, FIRST_NAME, PHONE_NUMBER, JOB_ID
FROM EMPLOYEES
WHERE SALARY > 10000 AND JOB_ID='SA_REP';

-- 4) 부서가 60이거나 이름이 A로 시작하는 시작하는 직원의 정보(이름, 급여, 부서)를  조회하시오.
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60 OR FIRST_NAME LIKE 'A%';


-- 5) 부서가 10이거나 50이거나 60번 부서의 직원의 정보(이름, 급여, 부서)를 조회하시오
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 50, 60);

-- 6) 이름이 3글자인 모든 사람의 정보를 조회하시오.
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '___';

-- 7) 전체 직원들중 직급이 'CLERK' 들을 조회 (종류가 많음)
SELECT FIRST_NAME, JOB_ID 
FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK';



